[package]
name = "mos-6500"
version = "0.1.0"
authors = ["Ryan Norris <rynorris@gmail.com>"]

[dependencies]
sdl2 = { version = "0.31", features = ["unsafe_textures"] }

[profile.release]
debug = true
