[package]
name = "mos-6500"
version = "0.1.0"
authors = ["Ryan Norris <rynorris@gmail.com>"]

[dependencies]
base64 = "0.10"
md-5 = "0.8"
sdl2 = { version = "0.31", features = ["unsafe_textures"] }

[profile.release]
debug = true

[profile.test]
opt-level = 3
